add_newline = true
command_timeout = 6000

[nodejs]
format = "[$symbol($version )]($style)"
style = "bold fg:#39bae6"

[character]
success_symbol = "[ ➜](bold #86b300) "
error_symbol = "[ ✗](bold #ff3333) "
vicmd_symbol = "[ V ➜](bold fg:#61afef)"

[directory]
truncation_length = 4
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold fg:#fc6b0a"

[git_branch]
format="[$symbol$branch]($style) "
style = "bold fg:#86b300"

[git_status]
format = '([\[$untracked$modified\]]($style) )'
style = "bold fg:#86b300"

[package]
disabled = true
